version: "2"
formatters:
  enable:
    - gofmt
    - goimports
    - golines
linters:
  enabled:
    - exhaustive
    - errname
    - errorlint
    - errchkjson
    - embeddedstructfieldcheck
    - containedctx
